Correct invalid example
hashicorp/terraform-provider-boundary pull request #161
Opened 2021-12-07 10:12 UTC by peterlindsten

Credential library vault resource had an invalid example

2021-12-07 10:12 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-boundary?pullRequest=161)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-boundary?pullRequest=161)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-boundary?pullRequest=161).</sub>

2021-12-18 03:23 UTC, louisruch requested changes
Hi there, thanks for the contribution.  Our docs are auto generated so the way to make this change would be to update the example in the `resource.tf` file here: https://github.com/hashicorp/terraform-provider-boundary/blob/main/examples/resources/boundary_credential_library_vault/resource.tf#L38
You can then run `make docs` or `go generate` to update the docs.

2021-12-20 15:15 UTC, peterlindsten commented
@louisruch Thanks for the detailed instruction.
Took a little bit to get the right go version to run on my setup - but I think this is correct now?

Ran the .tf file through terraform fmt, since it looked like the others were.

2021-12-20 15:44 UTC, louisruch approved these changes
Thanks again for the contribution

2021-12-20 15:44 UTC, merged