feat(oidc): OIDC Prompt Support
hashicorp/terraform-provider-boundary pull request #519
Opened 2023-11-21 21:22 UTC by elimt

Boundary OIDC method does not currently support passing in prompts during authentication. This change adds the capability of passing OIDC prompts. Prompts are optional OIDC parameters that determine the behaviour of the authentication server: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

# Changes
Add new optional `prompts` option to `boundary_auth_method_oidc` resource. `prompts` option are optional OIDC parameters that determine the behavior of the authentication server.

## Examples

1. OIDC Auth Method With 1 Prompt

```
resource "boundary_auth_method_oidc" "oidc_with_one_prompt" {
  api_url_prefix     = "https://XO-XO-XO-XO-XOXOXO.boundary.hashicorp.cloud:9200"
  client_id          = "eieio"
  client_secret      = "hvo_secret_XO"
  description        = "My Boundary OIDC Auth Method With Prompt"
  issuer             = "https://sts.windows.net/TENANT_ID/"
  scope_id           = "global"
  signing_algorithms = ["RS256"]
  prompts            = ["select_account"]
  type               = "oidc"
}
```

2. OIDC Auth Method With Multiple Prompts

```
resource "boundary_auth_method_oidc" "oidc_with_multiple_prompts" {
  api_url_prefix     = "https://XO-XO-XO-XO-XOXOXO.boundary.hashicorp.cloud:9200"
  client_id          = "eieio"
  client_secret      = "hvo_secret_XO"
  description        = "My Boundary OIDC Auth Method With Multiple Prompts"
  issuer             = "https://sts.windows.net/TENANT_ID/"
  scope_id           = "global"
  signing_algorithms = ["RS256"]
  prompts            = ["consent", "select_account"]
  type               = "oidc"
}
```

2023-11-21 22:16 UTC, elimt commented on go.mod
> +	github.com/hashicorp/boundary/sdk v0.0.41-0.20231121173019-2cd2d4ecfceb
**NOTE**: This will be updated with the new release once ready

2023-11-22 10:31 UTC, jimlambrt commented on internal/provider/resource_auth_method_oidc.go
> +			for _, alg := range prompts.([]interface{}) {
```suggestion
			for _, p := range prompts.([]interface{}) {
```

2023-11-22 10:41 UTC, jimlambrt requested changes
Looks good.  A few minor suggestions.

2023-11-22 10:41 UTC, jimlambrt commented on internal/provider/resource_auth_method_oidc.go
> +		for _, c := range prompts.([]interface{}) {
perhaps change `c` to `p`?

2023-11-22 10:41 UTC, jimlambrt commented on internal/provider/resource_auth_method_oidc.go
> +				Description: `The prompts passed to the identity provider to determine whether to prompt the end-user for reauthentication, account selection or consent. ` +
perhaps list the valid values?

2023-11-22 10:41 UTC, jimlambrt commented on CHANGELOG.md
> +* Add support for OIDC prompt. Prompts are optional OIDC parameters that determine the behavior of the authentication server.
```suggestion
* Add support for OIDC prompts. Using prompts, the Relying Party (RP) can customize the authentication and authorization flow to suit their specific needs and improve the user experience. [OIDC Authentication request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
```

2023-11-22 16:17 UTC, jimlambrt approved these changes
ty!

2023-12-13 21:05 UTC, merged