chore: replace deprecated arguments in provider example
hashicorp/terraform-provider-boundary pull request #617
Opened 2024-07-10 10:54 UTC by bschaatsbergen

2024-07-10 13:44 UTC, moduli requested changes
Thanks for catching this.

2024-07-10 13:44 UTC, moduli commented on docs/index.md
Instead of modifying this file directly, I believe you need to modify `examples/provider/provider.tf` first and then run `make docs` to regenerate this file.

2024-07-12 07:48 UTC, bschaatsbergen commented on docs/index.md
Thanks @moduli, fixed

2024-07-12 14:07 UTC, moduli commented on docs/index.md
@bschaatsbergen Looks good.

We may want to also update the example in `README.md`? Looks like there's an instance there.

2024-07-15 14:01 UTC, moduli approved these changes

2024-07-15 14:02 UTC, merged